# Generated by Django 5.2.6 on 2025-09-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main banner title', max_length=200)),
                ('subtitle', models.CharField(help_text='Banner subtitle/description', max_length=200)),
                ('badge_text', models.CharField(blank=True, help_text="Badge text (e.g., 'NEW ARRIVAL', 'SALE')", max_length=100)),
                ('background_color', models.CharField(default='bg-gradient-to-r from-blue-900 to-blue-700', help_text='Tailwind CSS background classes', max_length=100)),
                ('text_color', models.CharField(default='text-white', help_text='Tailwind CSS text color classes', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/backgrounds/%Y/%m/')),
                ('background_image_url', models.URLField(blank=True, help_text='External background image URL', max_length=500)),
                ('cta_text', models.CharField(default='Shop Now', help_text='Button text', max_length=50)),
                ('cta_link', models.CharField(default='/products', help_text='Link URL for the button', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is active')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which banners appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
