# Generated by Django 5.2.6 on 2025-09-19 09:58

import product_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Minimum size: 1920x600px. Recommended: 2560x800px. Aspect ratio: 2.5:1 to 4:1', null=True, upload_to='banners/backgrounds/%Y/%m/', validators=[product_management.models.validate_banner_image]),
        ),
    ]
