# Generated by Django 5.2.6 on 2025-09-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_alter_banner_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='sku',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=100, unique=True),
        ),
    ]
