# Generated by Django 5.2.6 on 2025-09-24 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_alter_product_price_alter_product_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount (KES)')], max_length=10, null=True),
        ),
    ]
