# Generated by Django 5.2.6 on 2025-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_remove_product_attributes_productvariation_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='product_management.productattribute'),
        ),
    ]
