# Generated by Django 5.2.6 on 2025-09-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_order_i_1d1c93_idx',
            old_name='payments_pa_order_i_7b2b91_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_be07d0_idx',
            old_name='payments_pa_user_id_90a46e_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_status_7ad4af_idx',
            old_name='payments_pa_status_a69e0c_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_payment_87c4c1_idx',
            old_name='payments_pa_payment_06bc9b_idx',
        ),
    ]
