# Generated by Django 5.2.6 on 2025-09-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_2ff9b7_idx',
            old_name='core_auditl_user_id_e7cc74_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_timesta_80074f_idx',
            old_name='core_auditl_timesta_1b01e9_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_action_d9fb24_idx',
            old_name='core_auditl_action_f30c19_idx',
        ),
    ]
